image: atlassian/default-image:3

pipelines:
  default:
    - step:
        name: Build and Push Docker Image
        services:
          - docker
        script:
          - az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
          - az acr login --name myContainerRegistry
          - docker build -t mycontainerregistry.azurecr.io/my-node-app:$BITBUCKET_BUILD_NUMBER .
          - docker push mycontainerregistry.azurecr.io/my-node-app:$BITBUCKET_BUILD_NUMBER

    - step:
        name: Deploy to AKS
        script:
          - az aks get-credentials --resource-group myResourceGroup --name myAKSCluster
          - kubectl apply -f k8s/deployment.yaml
